# 言語系

## Go

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
'''

# JavaScript

[[plugins]]
repo = 'jason0x43/vim-js-indent'
on_ft = ['javascript', 'typescript', 'html']
hook_add = '''
  let g:js_indent_typescript = 1
'''

## Python

[[plugins]]
repo = 'hdima/python-syntax'
on_ft = 'python'
hook_add = '''
  let python_highlight_all = 1
'''

[[plugins]]
repo = 'Yggdroot/indentLine'
on_ft = 'python'
hook_add = '''
  let g:indentLine_enabled = 1
  let g:indentLine_char = '│'
  let g:indentLine_color_term = 239
'''

## TOML

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

## TypeScript

[[plugins]]
repo = 'leafgarland/typescript-vim.git'
on_ft = 'typescript'
