[[plugins]]
repo = 'scrooloose/syntastic'
hook_add = '''
  let g:syntastic_python_checkers = ['pyflakes', 'pep8']
'''

[[plugins]]
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  let g:hybrid_use_iTerm_colors = 1
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

